### ISSUE TITLE
Password required to make backup, doesn't work to decrypt

### ISSUE THREAD

**Issue by inspire22** [Tikolu/WorldExporter#3]
Google no longer allows you to backup the app without any password.  I enter a short password 'a' then backup continues and this message comes up:

> om device. You may unplug your device now.
> Extracting backup file...
> Backup encrypted, enter password (will NOT be displayed):
> Password:
> Exception in thread "main" java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
> Caused by: java.lang.RuntimeException: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
>         at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:516)
>         at org.nick.abe.Main.main(Main.java:142)
>         ... 5 more
> Caused by: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
>         at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:128)
>         at javax.crypto.CipherInputStream.read(CipherInputStream.java:246)
>         at java.util.zip.InflaterInputStream.fill(Unknown Source)
>         at java.util.zip.InflaterInputStream.read(Unknown Source)
>         at java.io.FilterInputStream.read(Unknown Source)
>         at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:474)
>         ... 6 more
> Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
>         at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
>         at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
>         at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
>         at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
>         at javax.crypto.Cipher.doFinal(Cipher.java:2047)
>         at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:125)
>         ... 11 more
> Extracting archive...
> 
> ERRORS:
> Unexpected end of archive

I'm on windows 10, and the device is on android 11
galaxy s10e

**Comment by KITKATKILLER67** [comment]
yes

**Comment by MFn233** [comment]
Maybe my fork will help you.
I added a function that you can enter your password when extracting files.

**Comment by MFn233** [comment]
https://github.com/MFn233/WorldExporter-Next
